### ISSUE TITLE
Create process for shipping preforms to customers.

### ISSUE THREAD

**Issue by Andre-Samsa** [SamsaSoftware/samsa_docs#5]
Similar as the process for caps, but the difference should be that if we sell 20.000 pieces, and scan a qr-code and change the amount to 7000, one Sales_Shipment_Line is created with that qr-code and 7000 pieces.

**Comment by Andre-Samsa** [comment]
![image](https://user-images.githubusercontent.com/79149821/108085796-ff33c700-7075-11eb-8854-9498c35b6ba2.jpeg)

**Comment by relitodea** [comment]
this is an issue - we are creating 1 line for each extra aantal !!  If you have such amounts it will be a nightmare

**Comment by relitodea** [comment]
we will need to have the types defined when we create 1 LINE and when we create SEPARATE LINES

**Comment by Andre-Samsa** [comment]
When: "Posting_Group":"PREFORM" 

create 1 Sales_Shipment_Line per scanned qr-code with 

"Quantity": = extra aantal
"Unit_of_Measure_Code":"STUKS

**Comment by Andre-Samsa** [comment]
Test order VO2100071, for 10.000 preforms. I scanned  qr-code and put 1.000 in Extra aantal, 1 line was created but counts as 1, not as 1000.

**Comment by Andre-Samsa** [comment]
Does not work, but we can make it much easier, we will never send part of a preform pallet, just ship the pallet and make sure the pallet amount is transfered to NAV in STUKS.

**Comment by Andre-Samsa** [comment]
VO2100073 scanned pallet preforms with 11143 pieces(Stuks), Samsa sends 1 STUKS to NAV.

**Comment by relitodea** [comment]
Fixed - using Pallet aantal as input for calculating the total...

**Comment by Andre-Samsa** [comment]
Not solved scanned a pallet on order VO2100092, does register the pallet on the order but does not count the quantity.

shipping to nav will count it as 1.
